{% set name = "lyricsmaster" %}
{% set version = "2.8.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "758cc82db510d6abac65e34723f7bc2aaecdfd7cb0d320ad650a75468421fa1c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  entry_points:
    - lyricsmaster=lyricsmaster.cli:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - pytest
    - python
  run:
    - python
    - click >=6.0
    - lxml
    - beautifulsoup4
    - urllib3
    - pysocks
    - gevent
    - stem
    - certifi

test:
  imports:
    - lyricsmaster
  commands:
    - lyricsmaster --help


about:
  home: https://github.com/SekouD/lyricsmaster
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "LyricsMaster is a library for downloading lyrics from multiple lyrics providers. LyricWiki, AzLyrics, Genius, Lyrics007, MusixMatch and other lyrics provider are available"
  description: "LyricsMaster is a library\
    \ for downloading lyrics from multiple lyrics providers.\n\nThe following Lyrics Providers are supported:\n\n- Lyric Wikia\n- AzLyrics\n- Genius\n- Lyrics007\n- MusixMatch\n- The Original Hip-Hop (Rap)\
    \ Lyrics Archive - OHHLA.com\n- and more to come soon.\n\n\n* Free software: MIT license\n* Documentation: https://lyricsmaster.readthedocs.io.\n\n\nFeatures\n--------\n\n- Download Lyrics from LyricWiki,\
    \ AzLyrics, Genius, Lyrics007, MusixMatch, OHHLA and more.\n- Download Lyrics Asynchronously.\n- Can make requests over Tor for anonymous downloading of songs.\n- Easily save the lyrics on your computer.\n\n"
  doc_url: https://lyricsmaster.readthedocs.io/en/latest/
  dev_url: https://github.com/SekouD/lyricsmaster

extra:
  recipe-maintainers:
    - SekouD
