travis:
  secure:
    BINSTAR_TOKEN: SQSlrJm1USv3ywRF8i642f0qhIQmLmPXQklvoBoxIMvO9jmb762cgqhBGnpttHM0lGS6SDJPpWE1lf4IoCxGSw3oVDPLWJiDH+8YnEYF40qv7WIwVnNjuiWA3o2bDNW/REeAoLPS/gbWOAC/FuerKATVJoJTWh1dG2SUNKsmwPHg3RImpQ0ylJT2qchpG+g6lCFrE6PqOn83Juu6pLcKmEKIHkLxa41rxJ1wzn0rJIHfMQsHXC+Fx6+W0UO/zdO8uQE/zANgb9rMDt44C0It8wc7ppCeGXoAIAiK351pu+E2i3akxfDj6JRDO7YbjMD27R6NEzz9X905EL226HfpKtJa32b0jno2HChwhacSV+LQrrRfp/u0+gmG8b87l360y6RMI77v7KlyTUnX639iMEqCDtR4NKgP1PO6ewX5zMlD707KaDBAXjRw9X5D4TUzMFDpjbf7E5cHXZCruG3hdMCDgALdaWcrVfZ0DzQ5GwPnTObgfWb5FcMXqMrgp1Q8avwWCfWzRq5dQtiUn20Sh90LCocIAnhcgSrVb3C0CgKh9mPoyUzg0pmxgrFr9rccVxB5D+CvFK0//bh/wy8gtGHtL5d+VqWxrKTL4JKUQ6ucS/dSS6rmyQ/GEVPbolvOQM1gE6x4qqxaGkvNuClG2Tlj7Z1AcicXfNrpm+ylTeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
